#include "../src/application.hpp"
#include "../src/controls/tree_view.hpp"
#include "../src/controls/line_edit.hpp"

struct Hidden {
    int id = -1;
    Hidden(int id) : id{id} {}
};

int main(int argc, char **argv) {
    std::map<int, TreeNode<Hidden>*> nodes = {
        {2001, new TreeNode<Hidden>({new TextCellRenderer("Defender Great Sword I")}, new Hidden(-1))},
        {2002, new TreeNode<Hidden>({new TextCellRenderer("Defender Great Sword II")}, new Hidden(2001))},
        {2003, new TreeNode<Hidden>({new TextCellRenderer("Defender Great Sword III")}, new Hidden(2002))},
        {2004, new TreeNode<Hidden>({new TextCellRenderer("Defender Great Sword IV")}, new Hidden(2003))},
        {2005, new TreeNode<Hidden>({new TextCellRenderer("Defender Great Sword V")}, new Hidden(2004))},
        {1, new TreeNode<Hidden>({new TextCellRenderer("Buster Sword I")}, new Hidden(-1))},
        {2, new TreeNode<Hidden>({new TextCellRenderer("Buster Sword II")}, new Hidden(1))},
        {3, new TreeNode<Hidden>({new TextCellRenderer("Buster Sword III")}, new Hidden(2))},
        {4, new TreeNode<Hidden>({new TextCellRenderer("Buster Blade I")}, new Hidden(3))},
        {5, new TreeNode<Hidden>({new TextCellRenderer("Buster Blade II")}, new Hidden(4))},
        {6, new TreeNode<Hidden>({new TextCellRenderer("Buster Blade III")}, new Hidden(5))},
        {7, new TreeNode<Hidden>({new TextCellRenderer("Chrome Razor I")}, new Hidden(6))},
        {8, new TreeNode<Hidden>({new TextCellRenderer("Chrome Razor II")}, new Hidden(7))},
        {2006, new TreeNode<Hidden>({new TextCellRenderer("Chrome Deathscythe I")}, new Hidden(8))},
        {2007, new TreeNode<Hidden>({new TextCellRenderer("Chrome Deathscythe II")}, new Hidden(2006))},
        {2008, new TreeNode<Hidden>({new TextCellRenderer("Chrome Deathscythe III")}, new Hidden(2007))},
        {9, new TreeNode<Hidden>({new TextCellRenderer("Nergal Judicator")}, new Hidden(7))},
        {10, new TreeNode<Hidden>({new TextCellRenderer("Purgation's Atrocity")}, new Hidden(9))},
        {2009, new TreeNode<Hidden>({new TextCellRenderer("Ruinous Atrocity")}, new Hidden(10))},
        {11, new TreeNode<Hidden>({new TextCellRenderer("Thunder Blade I")}, new Hidden(3))},
        {12, new TreeNode<Hidden>({new TextCellRenderer("Thunder Blade II")}, new Hidden(11))},
        {13, new TreeNode<Hidden>({new TextCellRenderer("Lightning Punisher I")}, new Hidden(12))},
        {14, new TreeNode<Hidden>({new TextCellRenderer("Lightning Punisher II")}, new Hidden(13))},
        {15, new TreeNode<Hidden>({new TextCellRenderer("Lightning Punisher III")}, new Hidden(14))},
        {2010, new TreeNode<Hidden>({new TextCellRenderer("Lightning Punisher IV")}, new Hidden(15))},
        {2011, new TreeNode<Hidden>({new TextCellRenderer("Severing Bolt I")}, new Hidden(2010))},
        {2012, new TreeNode<Hidden>({new TextCellRenderer("Severing Bolt II")}, new Hidden(2011))},
        {16, new TreeNode<Hidden>({new TextCellRenderer("Freeze Blade I")}, new Hidden(11))},
        {17, new TreeNode<Hidden>({new TextCellRenderer("Freeze Blade II")}, new Hidden(16))},
        {18, new TreeNode<Hidden>({new TextCellRenderer("Frost Blaze I")}, new Hidden(17))},
        {19, new TreeNode<Hidden>({new TextCellRenderer("Frost Blaze II")}, new Hidden(18))},
        {2013, new TreeNode<Hidden>({new TextCellRenderer("Frost Blaze III")}, new Hidden(19))},
        {2014, new TreeNode<Hidden>({new TextCellRenderer("Icicle Fang")}, new Hidden(2013))},
        {2015, new TreeNode<Hidden>({new TextCellRenderer("Icicle Fang+")}, new Hidden(2014))},
        {2016, new TreeNode<Hidden>({new TextCellRenderer("Paladire")}, new Hidden(2015))},
        {3222, new TreeNode<Hidden>({new TextCellRenderer("Glacial Demon")}, new Hidden(2014))},
        {20, new TreeNode<Hidden>({new TextCellRenderer("Jagras Blade I")}, new Hidden(2))},
        {21, new TreeNode<Hidden>({new TextCellRenderer("Jagras Blade II")}, new Hidden(20))},
        {22, new TreeNode<Hidden>({new TextCellRenderer("Jagras Blade III")}, new Hidden(21))},
        {23, new TreeNode<Hidden>({new TextCellRenderer("Jagras Hacker I")}, new Hidden(22))},
        {24, new TreeNode<Hidden>({new TextCellRenderer("Jagras Hacker II")}, new Hidden(23))},
        {25, new TreeNode<Hidden>({new TextCellRenderer("Jagras Hacker III")}, new Hidden(24))},
        {2017, new TreeNode<Hidden>({new TextCellRenderer("Jagras Deathclaw I")}, new Hidden(25))},
        {2018, new TreeNode<Hidden>({new TextCellRenderer("Jagras Deathclaw II")}, new Hidden(2017))},
        {2019, new TreeNode<Hidden>({new TextCellRenderer("Mammoth Greataxe I")}, new Hidden(2017))},
        {2020, new TreeNode<Hidden>({new TextCellRenderer("Mammoth Greataxe II")}, new Hidden(2019))},
        {26, new TreeNode<Hidden>({new TextCellRenderer("Girros Blade I")}, new Hidden(20))},
        {27, new TreeNode<Hidden>({new TextCellRenderer("Girros Blade II")}, new Hidden(26))},
        {28, new TreeNode<Hidden>({new TextCellRenderer("Malady's Kiss I")}, new Hidden(27))},
        {29, new TreeNode<Hidden>({new TextCellRenderer("Malady's Kiss II")}, new Hidden(28))},
        {30, new TreeNode<Hidden>({new TextCellRenderer("Malady's Kiss III")}, new Hidden(29))},
        {2021, new TreeNode<Hidden>({new TextCellRenderer("Naaga Guillotine I")}, new Hidden(30))},
        {2022, new TreeNode<Hidden>({new TextCellRenderer("Naaga Guillotine II")}, new Hidden(2021))},
        {2023, new TreeNode<Hidden>({new TextCellRenderer("Hidden Blade I")}, new Hidden(2021))},
        {2024, new TreeNode<Hidden>({new TextCellRenderer("Hidden Blade II")}, new Hidden(2023))},
        {31, new TreeNode<Hidden>({new TextCellRenderer("Lava Blaze I")}, new Hidden(28))},
        {32, new TreeNode<Hidden>({new TextCellRenderer("Lava Blaze II")}, new Hidden(31))},
        {2025, new TreeNode<Hidden>({new TextCellRenderer("Pyre Cleaver I")}, new Hidden(32))},
        {2026, new TreeNode<Hidden>({new TextCellRenderer("Pyre Cleaver II")}, new Hidden(2025))},
        {2027, new TreeNode<Hidden>({new TextCellRenderer("Glavenus Blaze I")}, new Hidden(32))},
        {2028, new TreeNode<Hidden>({new TextCellRenderer("Glavenus Blaze II")}, new Hidden(2027))},
        {33, new TreeNode<Hidden>({new TextCellRenderer("Blooming Blade I")}, new Hidden(2))},
        {34, new TreeNode<Hidden>({new TextCellRenderer("Blooming Blade II")}, new Hidden(33))},
        {35, new TreeNode<Hidden>({new TextCellRenderer("Blooming Blade III")}, new Hidden(34))},
        {36, new TreeNode<Hidden>({new TextCellRenderer("Datura Blaze I")}, new Hidden(35))},
        {37, new TreeNode<Hidden>({new TextCellRenderer("Datura Blaze II")}, new Hidden(36))},
        {38, new TreeNode<Hidden>({new TextCellRenderer("Datura Blaze III")}, new Hidden(37))},
        {2029, new TreeNode<Hidden>({new TextCellRenderer("Datura Hellspine I")}, new Hidden(38))},
        {2030, new TreeNode<Hidden>({new TextCellRenderer("Datura Hellspine II")}, new Hidden(2029))},
        {2031, new TreeNode<Hidden>({new TextCellRenderer("Nyx Razor I")}, new Hidden(2029))},
        {2032, new TreeNode<Hidden>({new TextCellRenderer("Nyx Razor II")}, new Hidden(2031))},
        {39, new TreeNode<Hidden>({new TextCellRenderer("Flame Blade I")}, new Hidden(33))},
        {40, new TreeNode<Hidden>({new TextCellRenderer("Flame Blade II")}, new Hidden(39))},
        {41, new TreeNode<Hidden>({new TextCellRenderer("Red Wing")}, new Hidden(40))},
        {42, new TreeNode<Hidden>({new TextCellRenderer("Blue Wing")}, new Hidden(41))},
        {43, new TreeNode<Hidden>({new TextCellRenderer("Rathalos Glinsword")}, new Hidden(42))},
        {2033, new TreeNode<Hidden>({new TextCellRenderer("Rathalos Glinsword+")}, new Hidden(43))},
        {2034, new TreeNode<Hidden>({new TextCellRenderer("Rathflame Glinsword")}, new Hidden(2033))},
        {2035, new TreeNode<Hidden>({new TextCellRenderer("Rathalos Gleamsword")}, new Hidden(2034))},
        {44, new TreeNode<Hidden>({new TextCellRenderer("Bone Blade I")}, new Hidden(-1))},
        {45, new TreeNode<Hidden>({new TextCellRenderer("Bone Blade II")}, new Hidden(44))},
        {46, new TreeNode<Hidden>({new TextCellRenderer("Bone Blade III")}, new Hidden(45))},
        {47, new TreeNode<Hidden>({new TextCellRenderer("Bone Slasher I")}, new Hidden(46))},
        {48, new TreeNode<Hidden>({new TextCellRenderer("Bone Slasher II")}, new Hidden(47))},
        {49, new TreeNode<Hidden>({new TextCellRenderer("Bone Slasher III")}, new Hidden(48))},
        {50, new TreeNode<Hidden>({new TextCellRenderer("Giant Jawblade I")}, new Hidden(49))},
        {51, new TreeNode<Hidden>({new TextCellRenderer("Giant Jawblade II")}, new Hidden(50))},
        {2036, new TreeNode<Hidden>({new TextCellRenderer("Ogre's Jaw I")}, new Hidden(51))},
        {2037, new TreeNode<Hidden>({new TextCellRenderer("Ogre's Jaw II")}, new Hidden(2036))},
        {2038, new TreeNode<Hidden>({new TextCellRenderer("Ogre's Jaw III")}, new Hidden(2037))},
        {2039, new TreeNode<Hidden>({new TextCellRenderer("Icewing")}, new Hidden(2037))},
        {2040, new TreeNode<Hidden>({new TextCellRenderer("Winged Seraphyd")}, new Hidden(2039))},
        {2041, new TreeNode<Hidden>({new TextCellRenderer("Tiger Jawblade")}, new Hidden(2036))},
        {2042, new TreeNode<Hidden>({new TextCellRenderer("Tiger Jawblade+")}, new Hidden(2041))},
        {2043, new TreeNode<Hidden>({new TextCellRenderer("Tigrex Great Sword")}, new Hidden(2042))},
        {2044, new TreeNode<Hidden>({new TextCellRenderer("Accursed Blade")}, new Hidden(2041))},
        {2045, new TreeNode<Hidden>({new TextCellRenderer("Wildbite")}, new Hidden(2044))},
        {52, new TreeNode<Hidden>({new TextCellRenderer("Hazak Kys")}, new Hidden(50))},
        {53, new TreeNode<Hidden>({new TextCellRenderer("Leviathan's Fury")}, new Hidden(52))},
        {2046, new TreeNode<Hidden>({new TextCellRenderer("Monstrous Madness")}, new Hidden(53))},
        {2047, new TreeNode<Hidden>({new TextCellRenderer("Don Monstro")}, new Hidden(2046))},
        {54, new TreeNode<Hidden>({new TextCellRenderer("Flammenzahn")}, new Hidden(46))},
        {55, new TreeNode<Hidden>({new TextCellRenderer("Flammenzahn+")}, new Hidden(54))},
        {56, new TreeNode<Hidden>({new TextCellRenderer("Gnashing Flammenzahn")}, new Hidden(55))},
        {2048, new TreeNode<Hidden>({new TextCellRenderer("Gnashing Flammenzahn+")}, new Hidden(56))},
        {2049, new TreeNode<Hidden>({new TextCellRenderer("Lohenzahn")}, new Hidden(2048))},
        {2050, new TreeNode<Hidden>({new TextCellRenderer("Donnerzahn")}, new Hidden(2048))},
        {2051, new TreeNode<Hidden>({new TextCellRenderer("Donnerzahn+")}, new Hidden(2050))},
        {2052, new TreeNode<Hidden>({new TextCellRenderer("Fulguration's Edge")}, new Hidden(2051))},
        {57, new TreeNode<Hidden>({new TextCellRenderer("Aqua Slasher I")}, new Hidden(45))},
        {58, new TreeNode<Hidden>({new TextCellRenderer("Aqua Slasher II")}, new Hidden(57))},
        {59, new TreeNode<Hidden>({new TextCellRenderer("Aqua Slasher III")}, new Hidden(58))},
        {60, new TreeNode<Hidden>({new TextCellRenderer("Water Golem I")}, new Hidden(59))},
        {61, new TreeNode<Hidden>({new TextCellRenderer("Water Golem II")}, new Hidden(60))},
        {62, new TreeNode<Hidden>({new TextCellRenderer("Water Golem III")}, new Hidden(61))},
        {2053, new TreeNode<Hidden>({new TextCellRenderer("Water Golem IV")}, new Hidden(62))},
        {2054, new TreeNode<Hidden>({new TextCellRenderer("Laguna Golem I")}, new Hidden(2053))},
        {2055, new TreeNode<Hidden>({new TextCellRenderer("Laguna Golem II")}, new Hidden(2054))},
        {2056, new TreeNode<Hidden>({new TextCellRenderer("Beo Slasher I")}, new Hidden(62))},
        {2057, new TreeNode<Hidden>({new TextCellRenderer("Beo Slasher II")}, new Hidden(2056))},
        {63, new TreeNode<Hidden>({new TextCellRenderer("Carapace Buster I")}, new Hidden(45))},
        {64, new TreeNode<Hidden>({new TextCellRenderer("Carapace Buster II")}, new Hidden(63))},
        {65, new TreeNode<Hidden>({new TextCellRenderer("Carapace Buster III")}, new Hidden(64))},
        {66, new TreeNode<Hidden>({new TextCellRenderer("Barroth Shredder I")}, new Hidden(65))},
        {67, new TreeNode<Hidden>({new TextCellRenderer("Barroth Shredder II")}, new Hidden(66))},
        {68, new TreeNode<Hidden>({new TextCellRenderer("Barroth Shredder III")}, new Hidden(67))},
        {2058, new TreeNode<Hidden>({new TextCellRenderer("Barroth Greatedge I")}, new Hidden(68))},
        {2059, new TreeNode<Hidden>({new TextCellRenderer("Barroth Greatedge II")}, new Hidden(2058))},
        {2060, new TreeNode<Hidden>({new TextCellRenderer("Acid Shredder I")}, new Hidden(2058))},
        {2061, new TreeNode<Hidden>({new TextCellRenderer("Acid Shredder II")}, new Hidden(2060))},
        {69, new TreeNode<Hidden>({new TextCellRenderer("Spiked Blade I")}, new Hidden(63))},
        {70, new TreeNode<Hidden>({new TextCellRenderer("Spiked Blade II")}, new Hidden(69))},
        {71, new TreeNode<Hidden>({new TextCellRenderer("Radobaan Slab I")}, new Hidden(70))},
        {72, new TreeNode<Hidden>({new TextCellRenderer("Radobaan Slab II")}, new Hidden(71))},
        {73, new TreeNode<Hidden>({new TextCellRenderer("Radobaan Slab III")}, new Hidden(72))},
        {2062, new TreeNode<Hidden>({new TextCellRenderer("Radobaan Grindblade I")}, new Hidden(73))},
        {2063, new TreeNode<Hidden>({new TextCellRenderer("Radobaan Grindblade II")}, new Hidden(2062))},
        {2064, new TreeNode<Hidden>({new TextCellRenderer("Dios Blade")}, new Hidden(2062))},
        {2065, new TreeNode<Hidden>({new TextCellRenderer("Brach Attack")}, new Hidden(2064))},
        {74, new TreeNode<Hidden>({new TextCellRenderer("Dragonbone Cleaver I")}, new Hidden(-1))},
        {75, new TreeNode<Hidden>({new TextCellRenderer("Dragonbone Cleaver II")}, new Hidden(74))},
        {76, new TreeNode<Hidden>({new TextCellRenderer("Dragonbone Cleaver III")}, new Hidden(75))},
        {2066, new TreeNode<Hidden>({new TextCellRenderer("Dragonseal Sword I")}, new Hidden(76))},
        {2067, new TreeNode<Hidden>({new TextCellRenderer("Dragonseal Sword II")}, new Hidden(2066))},
        {2068, new TreeNode<Hidden>({new TextCellRenderer("Immovable Dharma")}, new Hidden(2066))},
        {77, new TreeNode<Hidden>({new TextCellRenderer("Thundersword")}, new Hidden(74))},
        {78, new TreeNode<Hidden>({new TextCellRenderer("Kirin Thundersword")}, new Hidden(77))},
        {79, new TreeNode<Hidden>({new TextCellRenderer("King Thundersword")}, new Hidden(78))},
        {2069, new TreeNode<Hidden>({new TextCellRenderer("Emperor Thundersword")}, new Hidden(79))},
        {80, new TreeNode<Hidden>({new TextCellRenderer("Magda Potestas I")}, new Hidden(74))},
        {81, new TreeNode<Hidden>({new TextCellRenderer("Magda Potestas II")}, new Hidden(80))},
        {2070, new TreeNode<Hidden>({new TextCellRenderer("Magdaros Volcanblade")}, new Hidden(81))},
        {82, new TreeNode<Hidden>({new TextCellRenderer("Blacksteel Chopper I")}, new Hidden(-1))},
        {83, new TreeNode<Hidden>({new TextCellRenderer("Blacksteel Chopper II")}, new Hidden(82))},
        {84, new TreeNode<Hidden>({new TextCellRenderer("Icesteel Edge")}, new Hidden(83))},
        {85, new TreeNode<Hidden>({new TextCellRenderer("Daora's Decimator")}, new Hidden(84))},
        {2071, new TreeNode<Hidden>({new TextCellRenderer("Daora's Tughril Beg")}, new Hidden(85))},
        {86, new TreeNode<Hidden>({new TextCellRenderer("Xeno Maliq")}, new Hidden(83))},
        {87, new TreeNode<Hidden>({new TextCellRenderer("Wyvern Jawblade")}, new Hidden(-1))},
        {88, new TreeNode<Hidden>({new TextCellRenderer("Great Wyvern Jawblade")}, new Hidden(87))},
        {2072, new TreeNode<Hidden>({new TextCellRenderer("Ultra Wyvern Jawblade")}, new Hidden(88))},
        {1150, new TreeNode<Hidden>({new TextCellRenderer("Berserker Sword")}, new Hidden(-1))},
        {1151, new TreeNode<Hidden>({new TextCellRenderer("Anguish")}, new Hidden(1150))},
        {2073, new TreeNode<Hidden>({new TextCellRenderer("Consummate Blade")}, new Hidden(1151))},
        {1188, new TreeNode<Hidden>({new TextCellRenderer("Wyvern Ignition 'Steel'")}, new Hidden(-1))},
        {1189, new TreeNode<Hidden>({new TextCellRenderer("Wyvern Ignition 'Impact'")}, new Hidden(1188))},
        {1190, new TreeNode<Hidden>({new TextCellRenderer("Empress Galea")}, new Hidden(-1))},
        {1191, new TreeNode<Hidden>({new TextCellRenderer("Empress Galea 'Blaze'")}, new Hidden(1190))},
        {2074, new TreeNode<Hidden>({new TextCellRenderer("Soulfire Edge 'Blaze'")}, new Hidden(1191))},
        {1192, new TreeNode<Hidden>({new TextCellRenderer("Empress Galea 'Ruin'")}, new Hidden(1190))},
        {2075, new TreeNode<Hidden>({new TextCellRenderer("Soulfire Edge 'Ruin'")}, new Hidden(1192))},
        {1193, new TreeNode<Hidden>({new TextCellRenderer("Empress Galea 'Styx'")}, new Hidden(1190))},
        {2076, new TreeNode<Hidden>({new TextCellRenderer("Soulfire Edge 'Styx'")}, new Hidden(1193))},
        {2077, new TreeNode<Hidden>({new TextCellRenderer("Frozen Speartuna")}, new Hidden(-1))},
        {2078, new TreeNode<Hidden>({new TextCellRenderer("Freezer Speartuna")}, new Hidden(2077))},
        {2079, new TreeNode<Hidden>({new TextCellRenderer("Xiphias Gladius")}, new Hidden(2078))},
        {3110, new TreeNode<Hidden>({new TextCellRenderer("Demon Rod")}, new Hidden(-1))},
        {3111, new TreeNode<Hidden>({new TextCellRenderer("Great Demon Rod")}, new Hidden(3110))},
        {3112, new TreeNode<Hidden>({new TextCellRenderer("Demonlord Goldrod")}, new Hidden(-1))},
        {3113, new TreeNode<Hidden>({new TextCellRenderer("Infernal Executioner")}, new Hidden(-1))},
        {3114, new TreeNode<Hidden>({new TextCellRenderer("Infernal Executioner+")}, new Hidden(3113))},
        {3115, new TreeNode<Hidden>({new TextCellRenderer("Lightbreak Blade")}, new Hidden(-1))},
        {3196, new TreeNode<Hidden>({new TextCellRenderer("Alatreon Great Sword")}, new Hidden(-1))},
        {3197, new TreeNode<Hidden>({new TextCellRenderer("Alatreon Revolution")}, new Hidden(3196))},
        {3236, new TreeNode<Hidden>({new TextCellRenderer("Fatalis Blade")}, new Hidden(-1))},
        {3237, new TreeNode<Hidden>({new TextCellRenderer("Black Fatalis Blade")}, new Hidden(3236))},
        {2080, new TreeNode<Hidden>({new TextCellRenderer("Guild Palace Blade")}, new Hidden(-1))},
        {2081, new TreeNode<Hidden>({new TextCellRenderer("Royal Venus Blade")}, new Hidden(2080))},
        {2082, new TreeNode<Hidden>({new TextCellRenderer("Defender Katana I")}, new Hidden(-1))},
        {2083, new TreeNode<Hidden>({new TextCellRenderer("Defender Katana II")}, new Hidden(2082))},
        {2084, new TreeNode<Hidden>({new TextCellRenderer("Defender Katana III")}, new Hidden(2083))},
        {2085, new TreeNode<Hidden>({new TextCellRenderer("Defender Katana IV")}, new Hidden(2084))},
        {2086, new TreeNode<Hidden>({new TextCellRenderer("Defender Katana V")}, new Hidden(2085))},
        {89, new TreeNode<Hidden>({new TextCellRenderer("Iron Katana I")}, new Hidden(-1))},
        {90, new TreeNode<Hidden>({new TextCellRenderer("Iron Katana II")}, new Hidden(89))},
        {91, new TreeNode<Hidden>({new TextCellRenderer("Iron Katana III")}, new Hidden(90))},
        {92, new TreeNode<Hidden>({new TextCellRenderer("Iron Grace I")}, new Hidden(91))},
        {93, new TreeNode<Hidden>({new TextCellRenderer("Iron Grace II")}, new Hidden(92))},
        {94, new TreeNode<Hidden>({new TextCellRenderer("Iron Grace III")}, new Hidden(93))},
        {95, new TreeNode<Hidden>({new TextCellRenderer("Iron Gospel I")}, new Hidden(94))},
        {96, new TreeNode<Hidden>({new TextCellRenderer("Iron Gospel II")}, new Hidden(95))},
        {2087, new TreeNode<Hidden>({new TextCellRenderer("Iron Eschaton I")}, new Hidden(96))},
        {2088, new TreeNode<Hidden>({new TextCellRenderer("Iron Eschaton II")}, new Hidden(2087))},
        {2089, new TreeNode<Hidden>({new TextCellRenderer("Iron Eschaton III")}, new Hidden(2088))},
        {2090, new TreeNode<Hidden>({new TextCellRenderer("Daito Crow")}, new Hidden(2088))},
        {2091, new TreeNode<Hidden>({new TextCellRenderer("Daito Wolf")}, new Hidden(2090))},
        {2092, new TreeNode<Hidden>({new TextCellRenderer("Usurper's Boltslicer")}, new Hidden(2087))},
        {2093, new TreeNode<Hidden>({new TextCellRenderer("Usurper Boltslicer+")}, new Hidden(2092))},
        {2094, new TreeNode<Hidden>({new TextCellRenderer("Despot's Boltbreaker")}, new Hidden(2093))},
        {97, new TreeNode<Hidden>({new TextCellRenderer("Nergal Reaver")}, new Hidden(95))},
        {98, new TreeNode<Hidden>({new TextCellRenderer("Extermination's Edge")}, new Hidden(97))},
        {2095, new TreeNode<Hidden>({new TextCellRenderer("Ruinous Extermination")}, new Hidden(98))},
        {99, new TreeNode<Hidden>({new TextCellRenderer("Flickering Glow I")}, new Hidden(91))},
        {100, new TreeNode<Hidden>({new TextCellRenderer("Flickering Glow II")}, new Hidden(99))},
        {101, new TreeNode<Hidden>({new TextCellRenderer("Dazzling Flash I")}, new Hidden(100))},
        {102, new TreeNode<Hidden>({new TextCellRenderer("Dazzling Flash II")}, new Hidden(101))},
        {103, new TreeNode<Hidden>({new TextCellRenderer("Dazzling Flash III")}, new Hidden(102))},
        {2096, new TreeNode<Hidden>({new TextCellRenderer("Blinding Blaze I")}, new Hidden(103))},
        {2097, new TreeNode<Hidden>({new TextCellRenderer("Blinding Blaze II")}, new Hidden(2096))},
        {2098, new TreeNode<Hidden>({new TextCellRenderer("Ambertooth I")}, new Hidden(2096))},
        {2099, new TreeNode<Hidden>({new TextCellRenderer("Ambertooth II")}, new Hidden(2098))},
        {3223, new TreeNode<Hidden>({new TextCellRenderer("Adularia Edge")}, new Hidden(2098))},
        {104, new TreeNode<Hidden>({new TextCellRenderer("First Dance I")}, new Hidden(90))},
        {105, new TreeNode<Hidden>({new TextCellRenderer("First Dance II")}, new Hidden(104))},
        {106, new TreeNode<Hidden>({new TextCellRenderer("First Dance III")}, new Hidden(105))},
        {107, new TreeNode<Hidden>({new TextCellRenderer("Last Dance I")}, new Hidden(106))},
        {108, new TreeNode<Hidden>({new TextCellRenderer("Last Dance II")}, new Hidden(107))},
        {109, new TreeNode<Hidden>({new TextCellRenderer("Last Dance III")}, new Hidden(108))},
        {2100, new TreeNode<Hidden>({new TextCellRenderer("Rafiq al-Nasr I")}, new Hidden(109))},
        {2101, new TreeNode<Hidden>({new TextCellRenderer("Rafiq al-Nasr II")}, new Hidden(2100))},
        {2102, new TreeNode<Hidden>({new TextCellRenderer("Hidden Saber")}, new Hidden(2100))},
        {2103, new TreeNode<Hidden>({new TextCellRenderer("Hidden Saber+")}, new Hidden(2102))},
        {2104, new TreeNode<Hidden>({new TextCellRenderer("Deepest Night")}, new Hidden(2103))},
        {110, new TreeNode<Hidden>({new TextCellRenderer("Brazenridge I")}, new Hidden(107))},
        {111, new TreeNode<Hidden>({new TextCellRenderer("Brazenridge II")}, new Hidden(110))},
        {2105, new TreeNode<Hidden>({new TextCellRenderer("Brazenreach I")}, new Hidden(111))},
        {2106, new TreeNode<Hidden>({new TextCellRenderer("Brazenreach II")}, new Hidden(2105))},
        {2107, new TreeNode<Hidden>({new TextCellRenderer("Glavenus Spada I")}, new Hidden(111))},
        {2108, new TreeNode<Hidden>({new TextCellRenderer("Glavenus Spada II")}, new Hidden(2107))},
        {112, new TreeNode<Hidden>({new TextCellRenderer("Wyvern Blade 'Leaf'")}, new Hidden(104))},
        {113, new TreeNode<Hidden>({new TextCellRenderer("Wyvern Blade 'Verde'")}, new Hidden(112))},
        {114, new TreeNode<Hidden>({new TextCellRenderer("Wyvern Blade 'Holly'")}, new Hidden(113))},
        {2109, new TreeNode<Hidden>({new TextCellRenderer("Wyvern Blade 'Blossom'")}, new Hidden(114))},
        {2110, new TreeNode<Hidden>({new TextCellRenderer("Wyvern Blade 'Blossom'+")}, new Hidden(2109))},
        {2111, new TreeNode<Hidden>({new TextCellRenderer("Wyvern Blade 'Luna'")}, new Hidden(2110))},
        {115, new TreeNode<Hidden>({new TextCellRenderer("Wyvern Blade 'Fall'")}, new Hidden(112))},
        {116, new TreeNode<Hidden>({new TextCellRenderer("Wyvern Blade 'Blood'")}, new Hidden(115))},
        {117, new TreeNode<Hidden>({new TextCellRenderer("Wyvern Blade 'Azure'")}, new Hidden(116))},
        {118, new TreeNode<Hidden>({new TextCellRenderer("Wyvern Blade 'Indigo'")}, new Hidden(117))},
        {2112, new TreeNode<Hidden>({new TextCellRenderer("Wyvern Blade 'Indigo'+")}, new Hidden(118))},
        {2113, new TreeNode<Hidden>({new TextCellRenderer("Wyvern Blade 'Empyrean'")}, new Hidden(2112))},
        {2114, new TreeNode<Hidden>({new TextCellRenderer("Wyvern Blade 'Pale'")}, new Hidden(2113))},
        {119, new TreeNode<Hidden>({new TextCellRenderer("Bone Shotel I")}, new Hidden(-1))},
        {120, new TreeNode<Hidden>({new TextCellRenderer("Bone Shotel II")}, new Hidden(119))},
        {121, new TreeNode<Hidden>({new TextCellRenderer("Bone Shotel III")}, new Hidden(120))},
        {122, new TreeNode<Hidden>({new TextCellRenderer("Hard Bone Shotel I")}, new Hidden(121))},
        {123, new TreeNode<Hidden>({new TextCellRenderer("Hard Bone Shotel II")}, new Hidden(122))},
        {124, new TreeNode<Hidden>({new TextCellRenderer("Hard Bone Shotel III")}, new Hidden(123))},
        {125, new TreeNode<Hidden>({new TextCellRenderer("Bone Reaper I")}, new Hidden(124))},
        {126, new TreeNode<Hidden>({new TextCellRenderer("Bone Reaper II")}, new Hidden(125))},
        {2115, new TreeNode<Hidden>({new TextCellRenderer("Grand Khopesh I")}, new Hidden(126))},
        {2116, new TreeNode<Hidden>({new TextCellRenderer("Grand Khopesh II")}, new Hidden(2115))},
        {2117, new TreeNode<Hidden>({new TextCellRenderer("Grand Khopesh III")}, new Hidden(2116))},
        {2118, new TreeNode<Hidden>({new TextCellRenderer("Icebrink")}, new Hidden(2116))},
        {2119, new TreeNode<Hidden>({new TextCellRenderer("Reverent Elusarca")}, new Hidden(2118))},
        {2120, new TreeNode<Hidden>({new TextCellRenderer("Tigrine Edge")}, new Hidden(2115))},
        {2121, new TreeNode<Hidden>({new TextCellRenderer("Tigrine Edge+")}, new Hidden(2120))},
        {2122, new TreeNode<Hidden>({new TextCellRenderer("Tigrine Need")}, new Hidden(2121))},
        {2123, new TreeNode<Hidden>({new TextCellRenderer("Tigerfang")}, new Hidden(2120))},
        {2124, new TreeNode<Hidden>({new TextCellRenderer("Ravenbite")}, new Hidden(2123))},
        {127, new TreeNode<Hidden>({new TextCellRenderer("Rookslayer Long Sword")}, new Hidden(124))},
        {128, new TreeNode<Hidden>({new TextCellRenderer("Bazel Varga Rookslayer")}, new Hidden(127))},
        {2125, new TreeNode<Hidden>({new TextCellRenderer("Rooksearer Long Sword")}, new Hidden(128))},
        {2126, new TreeNode<Hidden>({new TextCellRenderer("Bazel Prozio Rooksearer")}, new Hidden(2125))},
        {129, new TreeNode<Hidden>({new TextCellRenderer("Blazing Shotel I")}, new Hidden(121))},
        {130, new TreeNode<Hidden>({new TextCellRenderer("Blazing Shotel II")}, new Hidden(129))},
        {131, new TreeNode<Hidden>({new TextCellRenderer("Anja Scimitar I")}, new Hidden(130))},
        {132, new TreeNode<Hidden>({new TextCellRenderer("Anja Scimitar II")}, new Hidden(131))},
        {133, new TreeNode<Hidden>({new TextCellRenderer("Anja Scimitar III")}, new Hidden(132))},
        {2127, new TreeNode<Hidden>({new TextCellRenderer("Anja Direfang I")}, new Hidden(133))},
        {2128, new TreeNode<Hidden>({new TextCellRenderer("Anja Direfang II")}, new Hidden(2127))},
        {2129, new TreeNode<Hidden>({new TextCellRenderer("Gnashing Fulgur I")}, new Hidden(2127))},
        {2130, new TreeNode<Hidden>({new TextCellRenderer("Gnashing Fulgur II")}, new Hidden(2129))},
        {134, new TreeNode<Hidden>({new TextCellRenderer("Jyura Shotel I")}, new Hidden(120))},
        {135, new TreeNode<Hidden>({new TextCellRenderer("Jyura Shotel II")}, new Hidden(134))},
        {136, new TreeNode<Hidden>({new TextCellRenderer("Jyura Shotel III")}, new Hidden(135))},
        {137, new TreeNode<Hidden>({new TextCellRenderer("Dipterus I")}, new Hidden(136))},
        {138, new TreeNode<Hidden>({new TextCellRenderer("Dipterus II")}, new Hidden(137))},
        {139, new TreeNode<Hidden>({new TextCellRenderer("Dipterus III")}, new Hidden(138))},
        {2131, new TreeNode<Hidden>({new TextCellRenderer("Dipterus Varzea I")}, new Hidden(139))},
        {2132, new TreeNode<Hidden>({new TextCellRenderer("Dipterus Varzea II")}, new Hidden(2131))},
        {2133, new TreeNode<Hidden>({new TextCellRenderer("Mammoth Longblade I")}, new Hidden(139))},
        {2134, new TreeNode<Hidden>({new TextCellRenderer("Mammoth Longblade II")}, new Hidden(2133))},
        {140, new TreeNode<Hidden>({new TextCellRenderer("Hazak Grosser I")}, new Hidden(138))},
        {141, new TreeNode<Hidden>({new TextCellRenderer("Hazak Grosser II")}, new Hidden(140))},
        {2135, new TreeNode<Hidden>({new TextCellRenderer("Deathblade Vaal Grosser")}, new Hidden(141))},
        {2136, new TreeNode<Hidden>({new TextCellRenderer("Acid Scimitar I")}, new Hidden(141))},
        {2137, new TreeNode<Hidden>({new TextCellRenderer("Acid Scimitar II")}, new Hidden(2136))},
        {142, new TreeNode<Hidden>({new TextCellRenderer("Pulsar Shotel I")}, new Hidden(120))},
        {143, new TreeNode<Hidden>({new TextCellRenderer("Pulsar Shotel II")}, new Hidden(142))},
        {144, new TreeNode<Hidden>({new TextCellRenderer("Pulsar Shotel III")}, new Hidden(143))},
        {145, new TreeNode<Hidden>({new TextCellRenderer("Kadachi Fang I")}, new Hidden(144))},
        {146, new TreeNode<Hidden>({new TextCellRenderer("Kadachi Fang II")}, new Hidden(145))},
        {147, new TreeNode<Hidden>({new TextCellRenderer("Kadachi Fang III")}, new Hidden(146))},
        {2138, new TreeNode<Hidden>({new TextCellRenderer("Kadachi Daito I")}, new Hidden(147))},
        {2139, new TreeNode<Hidden>({new TextCellRenderer("Kadachi Daito II")}, new Hidden(2138))},
        {2140, new TreeNode<Hidden>({new TextCellRenderer("Crimson Viperfang I")}, new Hidden(2138))},
        {2141, new TreeNode<Hidden>({new TextCellRenderer("Crimson Viperfang II")}, new Hidden(2140))},
        {148, new TreeNode<Hidden>({new TextCellRenderer("Glacial Shotel I")}, new Hidden(143))},
        {149, new TreeNode<Hidden>({new TextCellRenderer("Glacial Shotel II")}, new Hidden(148))},
        {150, new TreeNode<Hidden>({new TextCellRenderer("Stealer")}, new Hidden(149))},
        {151, new TreeNode<Hidden>({new TextCellRenderer("Legia Stealer")}, new Hidden(150))},
        {2142, new TreeNode<Hidden>({new TextCellRenderer("Legia Stealer+")}, new Hidden(151))},
        {2143, new TreeNode<Hidden>({new TextCellRenderer("Hoarcry Stealer")}, new Hidden(2142))},
        {2144, new TreeNode<Hidden>({new TextCellRenderer("Apsara Glacia")}, new Hidden(2143))},
        {152, new TreeNode<Hidden>({new TextCellRenderer("Dark Shotel I")}, new Hidden(142))},
        {153, new TreeNode<Hidden>({new TextCellRenderer("Dark Shotel II")}, new Hidden(152))},
        {154, new TreeNode<Hidden>({new TextCellRenderer("Dark Scimitar I")}, new Hidden(153))},
        {155, new TreeNode<Hidden>({new TextCellRenderer("Dark Scimitar II")}, new Hidden(154))},
        {156, new TreeNode<Hidden>({new TextCellRenderer("Dark Scimitar III")}, new Hidden(155))},
        {2145, new TreeNode<Hidden>({new TextCellRenderer("Abyss Piercer I")}, new Hidden(156))},
        {2146, new TreeNode<Hidden>({new TextCellRenderer("Abyss Piercer II")}, new Hidden(2145))},
        {2147, new TreeNode<Hidden>({new TextCellRenderer("Brachydios Scimitar I")}, new Hidden(2145))},
        {2148, new TreeNode<Hidden>({new TextCellRenderer("Brachydios Scimitar II")}, new Hidden(2147))},
        {157, new TreeNode<Hidden>({new TextCellRenderer("Dragonbone Stabber I")}, new Hidden(-1))},
        {158, new TreeNode<Hidden>({new TextCellRenderer("Dragonbone Stabber II")}, new Hidden(157))},
        {159, new TreeNode<Hidden>({new TextCellRenderer("Dragonbone Stabber III")}, new Hidden(158))},
        {2149, new TreeNode<Hidden>({new TextCellRenderer("Dragonseal Aldblade I")}, new Hidden(159))},
        {2150, new TreeNode<Hidden>({new TextCellRenderer("Dragonseal Aldblade II")}, new Hidden(2149))},
        {2151, new TreeNode<Hidden>({new TextCellRenderer("Radiant Flow")}, new Hidden(2149))},
        {160, new TreeNode<Hidden>({new TextCellRenderer("Magda Facultas I")}, new Hidden(157))},
        {161, new TreeNode<Hidden>({new TextCellRenderer("Magda Facultas II")}, new Hidden(160))},
        {2152, new TreeNode<Hidden>({new TextCellRenderer("Magdaros Volcansword")}, new Hidden(161))},
        {2153, new TreeNode<Hidden>({new TextCellRenderer("Hydra Tornaria")}, new Hidden(161))},
        {2154, new TreeNode<Hidden>({new TextCellRenderer("Black Tornaria")}, new Hidden(2153))},
        {162, new TreeNode<Hidden>({new TextCellRenderer("Blacksteel Long Sword I")}, new Hidden(-1))},
        {163, new TreeNode<Hidden>({new TextCellRenderer("Blacksteel Long Sword II")}, new Hidden(162))},
        {164, new TreeNode<Hidden>({new TextCellRenderer("Imperial Saber")}, new Hidden(163))},
        {165, new TreeNode<Hidden>({new TextCellRenderer("Imperial Shimmer")}, new Hidden(164))},
        {2155, new TreeNode<Hidden>({new TextCellRenderer("Imperial Flickerflame")}, new Hidden(165))},
        {166, new TreeNode<Hidden>({new TextCellRenderer("Xeno Cypher")}, new Hidden(163))},
        {167, new TreeNode<Hidden>({new TextCellRenderer("Supremacy Blade")}, new Hidden(-1))},
        {168, new TreeNode<Hidden>({new TextCellRenderer("Divine Slasher")}, new Hidden(167))},
        {2156, new TreeNode<Hidden>({new TextCellRenderer("Hellish Slasher")}, new Hidden(168))},
        {1152, new TreeNode<Hidden>({new TextCellRenderer("Reaver 'Cruelty'")}, new Hidden(-1))},
        {1153, new TreeNode<Hidden>({new TextCellRenderer("Reaver 'Calamity'")}, new Hidden(1152))},
        {2157, new TreeNode<Hidden>({new TextCellRenderer("Consummate Katana")}, new Hidden(1153))},
        {169, new TreeNode<Hidden>({new TextCellRenderer("Azure Star Blade")}, new Hidden(-1))},
        {1187, new TreeNode<Hidden>({new TextCellRenderer("Azure Star 'Dragon Dance'")}, new Hidden(169))},
        {1194, new TreeNode<Hidden>({new TextCellRenderer("Empress Sword")}, new Hidden(-1))},
        {1195, new TreeNode<Hidden>({new TextCellRenderer("Empress Sword 'Blaze'")}, new Hidden(1194))},
        {2158, new TreeNode<Hidden>({new TextCellRenderer("Soulfire Lash 'Blaze'")}, new Hidden(1195))},
        {1196, new TreeNode<Hidden>({new TextCellRenderer("Empress Sword 'Ruin'")}, new Hidden(1194))},
        {2159, new TreeNode<Hidden>({new TextCellRenderer("Soulfire Lash 'Ruin'")}, new Hidden(1196))},
        {1197, new TreeNode<Hidden>({new TextCellRenderer("Empress Sword 'Styx'")}, new Hidden(1194))},
        {2160, new TreeNode<Hidden>({new TextCellRenderer("Soulfire Lash 'Styx'")}, new Hidden(1197))},
        {3116, new TreeNode<Hidden>({new TextCellRenderer("Demon Halberd")}, new Hidden(-1))},
        {3117, new TreeNode<Hidden>({new TextCellRenderer("Great Demon Halberd")}, new Hidden(3116))},
        {3118, new TreeNode<Hidden>({new TextCellRenderer("Demonlord Halberd")}, new Hidden(-1))},
        {3119, new TreeNode<Hidden>({new TextCellRenderer("Brimstren Drakebone")}, new Hidden(-1))},
        {3120, new TreeNode<Hidden>({new TextCellRenderer("Stygian Gula")}, new Hidden(3119))},
        {3121, new TreeNode<Hidden>({new TextCellRenderer("Lightbreak Edge")}, new Hidden(-1))},
        {3238, new TreeNode<Hidden>({new TextCellRenderer("Dark Claw")}, new Hidden(-1))},
        {3239, new TreeNode<Hidden>({new TextCellRenderer("Dark Claw 'Demise'")}, new Hidden(3238))},
        {3240, new TreeNode<Hidden>({new TextCellRenderer("Fatalis Sickle")}, new Hidden(-1))},
        {3241, new TreeNode<Hidden>({new TextCellRenderer("Fatalis Zaggespanon")}, new Hidden(3240))},
        {2161, new TreeNode<Hidden>({new TextCellRenderer("Mad Scavenger Pickaxe")}, new Hidden(-1))},
        {2162, new TreeNode<Hidden>({new TextCellRenderer("Demon Scavenger Pickaxe")}, new Hidden(2161))},
        {2163, new TreeNode<Hidden>({new TextCellRenderer("Guild Palace Rapier")}, new Hidden(-1))},
        {2164, new TreeNode<Hidden>({new TextCellRenderer("Royal Captain Rapier")}, new Hidden(2163))},
        {2165, new TreeNode<Hidden>({new TextCellRenderer("Defender Warhatchet I")}, new Hidden(-1))},
        {2166, new TreeNode<Hidden>({new TextCellRenderer("Defender Warhatchet II")}, new Hidden(2165))},
        {2167, new TreeNode<Hidden>({new TextCellRenderer("Defender Warhatchet III")}, new Hidden(2166))},
        {2168, new TreeNode<Hidden>({new TextCellRenderer("Defender Warhatchet IV")}, new Hidden(2167))},
        {2169, new TreeNode<Hidden>({new TextCellRenderer("Defender Warhatchet V")}, new Hidden(2168))},
        {170, new TreeNode<Hidden>({new TextCellRenderer("Hunter's Knife I")}, new Hidden(-1))},
        {171, new TreeNode<Hidden>({new TextCellRenderer("Hunter's Knife II")}, new Hidden(170))},
        {172, new TreeNode<Hidden>({new TextCellRenderer("Hunter's Knife III")}, new Hidden(171))},
        {173, new TreeNode<Hidden>({new TextCellRenderer("Steel Knife I")}, new Hidden(172))},
        {174, new TreeNode<Hidden>({new TextCellRenderer("Steel Knife II")}, new Hidden(173))},
        {175, new TreeNode<Hidden>({new TextCellRenderer("Steel Knife III")}, new Hidden(174))},
        {176, new TreeNode<Hidden>({new TextCellRenderer("Chrome Slicer I")}, new Hidden(175))},
        {177, new TreeNode<Hidden>({new TextCellRenderer("Chrome Slicer II")}, new Hidden(176))},
        {2170, new TreeNode<Hidden>({new TextCellRenderer("Chrome Knight Sword I")}, new Hidden(177))},
        {2171, new TreeNode<Hidden>({new TextCellRenderer("Chrome Knight Sword II")}, new Hidden(2170))},
        {2172, new TreeNode<Hidden>({new TextCellRenderer("Chrome Knight Sword III")}, new Hidden(2171))},
        {178, new TreeNode<Hidden>({new TextCellRenderer("Nergal Jack")}, new Hidden(176))},
        {179, new TreeNode<Hidden>({new TextCellRenderer("Eradication Vanguard")}, new Hidden(178))},
        {2173, new TreeNode<Hidden>({new TextCellRenderer("Ruinous Madness")}, new Hidden(179))},
        {180, new TreeNode<Hidden>({new TextCellRenderer("Flame Knife I")}, new Hidden(173))},
        {181, new TreeNode<Hidden>({new TextCellRenderer("Flame Knife II")}, new Hidden(180))},
        {182, new TreeNode<Hidden>({new TextCellRenderer("Heat Edge")}, new Hidden(181))},
        {183, new TreeNode<Hidden>({new TextCellRenderer("Corona")}, new Hidden(182))},
        {2174, new TreeNode<Hidden>({new TextCellRenderer("Corona+")}, new Hidden(183))},
        {2175, new TreeNode<Hidden>({new TextCellRenderer("Blue Corona")}, new Hidden(2174))},
        {2176, new TreeNode<Hidden>({new TextCellRenderer("Platinum Dawn")}, new Hidden(2175))},
        {184, new TreeNode<Hidden>({new TextCellRenderer("Heavy Bang")}, new Hidden(173))},
        {185, new TreeNode<Hidden>({new TextCellRenderer("Heavy Bang+")}, new Hidden(184))},
        {186, new TreeNode<Hidden>({new TextCellRenderer("Master Bang")}, new Hidden(185))},
        {2177, new TreeNode<Hidden>({new TextCellRenderer("Legacy Bang")}, new Hidden(186))},
        {2178, new TreeNode<Hidden>({new TextCellRenderer("Legendary Bang")}, new Hidden(2177))},
        {187, new TreeNode<Hidden>({new TextCellRenderer("Aqua Messer I")}, new Hidden(171))},
        {188, new TreeNode<Hidden>({new TextCellRenderer("Aqua Messer II")}, new Hidden(187))},
        {189, new TreeNode<Hidden>({new TextCellRenderer("Aqua Messer III")}, new Hidden(188))},
        {190, new TreeNode<Hidden>({new TextCellRenderer("Rogue Wave I")}, new Hidden(189))},
        {191, new TreeNode<Hidden>({new TextCellRenderer("Rogue Wave II")}, new Hidden(190))},
        {192, new TreeNode<Hidden>({new TextCellRenderer("Rogue Wave III")}, new Hidden(191))},
        {2179, new TreeNode<Hidden>({new TextCellRenderer("Rogue Wave IV")}, new Hidden(192))},
        {2180, new TreeNode<Hidden>({new TextCellRenderer("Laguna Blossom I")}, new Hidden(2179))},
        {2181, new TreeNode<Hidden>({new TextCellRenderer("Laguna Blossom II")}, new Hidden(2180))},
        {2182, new TreeNode<Hidden>({new TextCellRenderer("Icicle Spike")}, new Hidden(2179))},
        {2183, new TreeNode<Hidden>({new TextCellRenderer("Icicle Spike+")}, new Hidden(2182))},
        {2184, new TreeNode<Hidden>({new TextCellRenderer("Nardebosche")}, new Hidden(2183))},
        {3224, new TreeNode<Hidden>({new TextCellRenderer("Silverbosche")}, new Hidden(2182))},
        {193, new TreeNode<Hidden>({new TextCellRenderer("Glacial Grace I")}, new Hidden(188))},
        {194, new TreeNode<Hidden>({new TextCellRenderer("Glacial Grace II")}, new Hidden(193))},
        {195, new TreeNode<Hidden>({new TextCellRenderer("Rimespire")}, new Hidden(194))},
        {196, new TreeNode<Hidden>({new TextCellRenderer("Legia Rimespire")}, new Hidden(195))},
        {2185, new TreeNode<Hidden>({new TextCellRenderer("Legia Rimespire+")}, new Hidden(196))},
        {2186, new TreeNode<Hidden>({new TextCellRenderer("Hoarcry Rimespire")}, new Hidden(2185))},
        {2187, new TreeNode<Hidden>({new TextCellRenderer("Nephilim Glacia")}, new Hidden(2186))},
        {197, new TreeNode<Hidden>({new TextCellRenderer("Princess Rapier")}, new Hidden(187))},
        {198, new TreeNode<Hidden>({new TextCellRenderer("Queen Rapier")}, new Hidden(197))},
        {199, new TreeNode<Hidden>({new TextCellRenderer("Queen Rose")}, new Hidden(198))},
        {200, new TreeNode<Hidden>({new TextCellRenderer("Royal Rose")}, new Hidden(199))},
        {2188, new TreeNode<Hidden>({new TextCellRenderer("Royal Rose+")}, new Hidden(200))},
        {2189, new TreeNode<Hidden>({new TextCellRenderer("Rose Highness")}, new Hidden(2188))},
        {2190, new TreeNode<Hidden>({new TextCellRenderer("Lunatic Rose")}, new Hidden(2189))},
        {201, new TreeNode<Hidden>({new TextCellRenderer("Lumu Knife I")}, new Hidden(187))},
        {202, new TreeNode<Hidden>({new TextCellRenderer("Lumu Knife II")}, new Hidden(201))},
        {203, new TreeNode<Hidden>({new TextCellRenderer("Lumu Tabar I")}, new Hidden(202))},
        {204, new TreeNode<Hidden>({new TextCellRenderer("Lumu Tabar II")}, new Hidden(203))},
        {205, new TreeNode<Hidden>({new TextCellRenderer("Lumu Tabar III")}, new Hidden(204))},
        {2191, new TreeNode<Hidden>({new TextCellRenderer("Lumu Nightmare I")}, new Hidden(205))},
        {2192, new TreeNode<Hidden>({new TextCellRenderer("Lumu Nightmare II")}, new Hidden(2191))},
        {2193, new TreeNode<Hidden>({new TextCellRenderer("Nyx Tabar I")}, new Hidden(205))},
        {2194, new TreeNode<Hidden>({new TextCellRenderer("Nyx Tabar II")}, new Hidden(2193))},
        {206, new TreeNode<Hidden>({new TextCellRenderer("Blooming Knife I")}, new Hidden(171))},
        {207, new TreeNode<Hidden>({new TextCellRenderer("Blooming Knife II")}, new Hidden(206))},
        {208, new TreeNode<Hidden>({new TextCellRenderer("Blooming Knife III")}, new Hidden(207))},
        {209, new TreeNode<Hidden>({new TextCellRenderer("Datura Blossom I")}, new Hidden(208))},
        {210, new TreeNode<Hidden>({new TextCellRenderer("Datura Blossom II")}, new Hidden(209))},
        {211, new TreeNode<Hidden>({new TextCellRenderer("Datura Blossom III")}, new Hidden(210))},
        {2195, new TreeNode<Hidden>({new TextCellRenderer("Datura Florescence I")}, new Hidden(211))},
        {2196, new TreeNode<Hidden>({new TextCellRenderer("Datura Florescence II")}, new Hidden(2195))},
        {2197, new TreeNode<Hidden>({new TextCellRenderer("Dios Edge")}, new Hidden(2195))},
        {2198, new TreeNode<Hidden>({new TextCellRenderer("Booming Barrage")}, new Hidden(2197))},
        {212, new TreeNode<Hidden>({new TextCellRenderer("Girros Knife I")}, new Hidden(206))},
        {213, new TreeNode<Hidden>({new TextCellRenderer("Girros Knife II")}, new Hidden(212))},
        {214, new TreeNode<Hidden>({new TextCellRenderer("Malady's Tabar I")}, new Hidden(213))},
        {215, new TreeNode<Hidden>({new TextCellRenderer("Malady's Tabar II")}, new Hidden(214))},
        {216, new TreeNode<Hidden>({new TextCellRenderer("Malady's Tabar III")}, new Hidden(215))},
        {2199, new TreeNode<Hidden>({new TextCellRenderer("Naaga Seax I")}, new Hidden(216))},
        {2200, new TreeNode<Hidden>({new TextCellRenderer("Naaga Seax II")}, new Hidden(2199))},
        {2201, new TreeNode<Hidden>({new TextCellRenderer("Hidden Edge")}, new Hidden(2199))},
        {2202, new TreeNode<Hidden>({new TextCellRenderer("Hidden Edge+")}, new Hidden(2201))},
        {2203, new TreeNode<Hidden>({new TextCellRenderer("Flash in the Night")}, new Hidden(2202))},
        {217, new TreeNode<Hidden>({new TextCellRenderer("Bone Kukri I")}, new Hidden(-1))},
        {218, new TreeNode<Hidden>({new TextCellRenderer("Bone Kukri II")}, new Hidden(217))},
        {219, new TreeNode<Hidden>({new TextCellRenderer("Bone Kukri III")}, new Hidden(218))},
        {220, new TreeNode<Hidden>({new TextCellRenderer("Chief Kukri I")}, new Hidden(219))},
        {221, new TreeNode<Hidden>({new TextCellRenderer("Chief Kukri II")}, new Hidden(220))},
        {222, new TreeNode<Hidden>({new TextCellRenderer("Chief Kukri III")}, new Hidden(221))},
        {223, new TreeNode<Hidden>({new TextCellRenderer("Grand Barong I")}, new Hidden(222))},
        {224, new TreeNode<Hidden>({new TextCellRenderer("Grand Barong II")}, new Hidden(223))},
        {2204, new TreeNode<Hidden>({new TextCellRenderer("Radobaan Os I")}, new Hidden(224))},
        {2205, new TreeNode<Hidden>({new TextCellRenderer("Radobaan Os II")}, new Hidden(2204))},
        {2206, new TreeNode<Hidden>({new TextCellRenderer("Radobaan Os III")}, new Hidden(2205))},
        {2207, new TreeNode<Hidden>({new TextCellRenderer("Icegale")}, new Hidden(2205))},
        {2208, new TreeNode<Hidden>({new TextCellRenderer("Noble Ana Palas")}, new Hidden(2207))},
        {225, new TreeNode<Hidden>({new TextCellRenderer("Spiked Edge I")}, new Hidden(219))},
        {226, new TreeNode<Hidden>({new TextCellRenderer("Spiked Edge II")}, new Hidden(225))},
        {227, new TreeNode<Hidden>({new TextCellRenderer("Baan Claw I")}, new Hidden(226))},
        {228, new TreeNode<Hidden>({new TextCellRenderer("Baan Claw II")}, new Hidden(227))},
        {229, new TreeNode<Hidden>({new TextCellRenderer("Baan Claw III")}, new Hidden(228))},
        {2209, new TreeNode<Hidden>({new TextCellRenderer("Radobaan Osseus I")}, new Hidden(229))},
        {2210, new TreeNode<Hidden>({new TextCellRenderer("Radobaan Osseus II")}, new Hidden(2209))},
        {2211, new TreeNode<Hidden>({new TextCellRenderer("Acid Razor I")}, new Hidden(2209))},
        {2212, new TreeNode<Hidden>({new TextCellRenderer("Acid Razor II")}, new Hidden(2211))},
        {230, new TreeNode<Hidden>({new TextCellRenderer("Jagras Edge I")}, new Hidden(218))},
        {231, new TreeNode<Hidden>({new TextCellRenderer("Jagras Edge II")}, new Hidden(230))},
        {232, new TreeNode<Hidden>({new TextCellRenderer("Jagras Edge III")}, new Hidden(231))},
        {233, new TreeNode<Hidden>({new TextCellRenderer("Jagras Garotte I")}, new Hidden(232))},
        {234, new TreeNode<Hidden>({new TextCellRenderer("Jagras Garotte II")}, new Hidden(233))},
        {235, new TreeNode<Hidden>({new TextCellRenderer("Jagras Garotte III")}, new Hidden(234))},
        {2213, new TreeNode<Hidden>({new TextCellRenderer("Saber's Gullet I")}, new Hidden(235))},
        {2214, new TreeNode<Hidden>({new TextCellRenderer("Saber's Gullet II")}, new Hidden(2213))},
        {2215, new TreeNode<Hidden>({new TextCellRenderer("Rex Talon")}, new Hidden(2213))},
        {2216, new TreeNode<Hidden>({new TextCellRenderer("Rex Talon+")}, new Hidden(2215))},
        {2217, new TreeNode<Hidden>({new TextCellRenderer("Tigrex Sword")}, new Hidden(2216))},
        {2218, new TreeNode<Hidden>({new TextCellRenderer("Accursed Claw")}, new Hidden(2215))},
        {2219, new TreeNode<Hidden>({new TextCellRenderer("Stonebite")}, new Hidden(2218))},
        {236, new TreeNode<Hidden>({new TextCellRenderer("Thunder Edge I")}, new Hidden(230))},
        {237, new TreeNode<Hidden>({new TextCellRenderer("Thunder Edge II")}, new Hidden(236))},
        {238, new TreeNode<Hidden>({new TextCellRenderer("Lightning Nemesis I")}, new Hidden(237))},
        {239, new TreeNode<Hidden>({new TextCellRenderer("Lightning Nemesis II")}, new Hidden(238))},
        {240, new TreeNode<Hidden>({new TextCellRenderer("Lightning Nemesis III")}, new Hidden(239))},
        {2220, new TreeNode<Hidden>({new TextCellRenderer("Lightning Nemesis IV")}, new Hidden(240))},
        {2221, new TreeNode<Hidden>({new TextCellRenderer("Usurper's Firebolt")}, new Hidden(2220))},
        {2222, new TreeNode<Hidden>({new TextCellRenderer("Usurper's Firebolt+")}, new Hidden(2221))},
        {2223, new TreeNode<Hidden>({new TextCellRenderer("Despot's Crookbolt")}, new Hidden(2222))},
        {241, new TreeNode<Hidden>({new TextCellRenderer("Carapace Edge I")}, new Hidden(218))},
        {242, new TreeNode<Hidden>({new TextCellRenderer("Carapace Edge II")}, new Hidden(241))},
        {243, new TreeNode<Hidden>({new TextCellRenderer("Carapace Edge III")}, new Hidden(242))},
        {244, new TreeNode<Hidden>({new TextCellRenderer("Barroth Club I")}, new Hidden(243))},
        {245, new TreeNode<Hidden>({new TextCellRenderer("Barroth Club II")}, new Hidden(244))},
        {246, new TreeNode<Hidden>({new TextCellRenderer("Barroth Club III")}, new Hidden(245))},
        {2224, new TreeNode<Hidden>({new TextCellRenderer("Barroth Slicer I")}, new Hidden(246))},
        {2225, new TreeNode<Hidden>({new TextCellRenderer("Barroth Slicer II")}, new Hidden(2224))},
        {2226, new TreeNode<Hidden>({new TextCellRenderer("Glavenus Razor I")}, new Hidden(2224))},
        {2227, new TreeNode<Hidden>({new TextCellRenderer("Glavenus Razor II")}, new Hidden(2226))},
        {247, new TreeNode<Hidden>({new TextCellRenderer("Blazing Edge I")}, new Hidden(241))},
        {248, new TreeNode<Hidden>({new TextCellRenderer("Blazing Edge II")}, new Hidden(247))},
        {249, new TreeNode<Hidden>({new TextCellRenderer("Flammensucher")}, new Hidden(248))},
        {250, new TreeNode<Hidden>({new TextCellRenderer("Gnashing Flammensucher")}, new Hidden(249))},
        {2228, new TreeNode<Hidden>({new TextCellRenderer("Gnashing Flammensucher+")}, new Hidden(250))},
        {2229, new TreeNode<Hidden>({new TextCellRenderer("Lohensieger")}, new Hidden(2228))},
        {2230, new TreeNode<Hidden>({new TextCellRenderer("Donnersieger")}, new Hidden(2228))},
        {2231, new TreeNode<Hidden>({new TextCellRenderer("Donnersieger+")}, new Hidden(2230))},
        {2232, new TreeNode<Hidden>({new TextCellRenderer("Fulguration's Talon")}, new Hidden(2231))},
        {251, new TreeNode<Hidden>({new TextCellRenderer("Dragonbone Sword I")}, new Hidden(-1))},
        {252, new TreeNode<Hidden>({new TextCellRenderer("Dragonbone Sword II")}, new Hidden(251))},
        {253, new TreeNode<Hidden>({new TextCellRenderer("Dragonbone Sword III")}, new Hidden(252))},
        {2233, new TreeNode<Hidden>({new TextCellRenderer("Dragonseal Aldsword I")}, new Hidden(253))},
        {2234, new TreeNode<Hidden>({new TextCellRenderer("Dragonseal Aldsword II")}, new Hidden(2233))},
        {2235, new TreeNode<Hidden>({new TextCellRenderer("Manifested Lotus")}, new Hidden(2233))},
        {254, new TreeNode<Hidden>({new TextCellRenderer("Fulminator")}, new Hidden(251))},
        {255, new TreeNode<Hidden>({new TextCellRenderer("Thunderbolt Sword I")}, new Hidden(254))},
        {256, new TreeNode<Hidden>({new TextCellRenderer("Thunderbolt Sword II")}, new Hidden(255))},
        {2236, new TreeNode<Hidden>({new TextCellRenderer("Ephemeral Fulminator")}, new Hidden(256))},
        {2237, new TreeNode<Hidden>({new TextCellRenderer("Hydros Discus")}, new Hidden(256))},
        {257, new TreeNode<Hidden>({new TextCellRenderer("Blacksteel Sword I")}, new Hidden(-1))},
        {258, new TreeNode<Hidden>({new TextCellRenderer("Blacksteel Sword II")}, new Hidden(257))},
        {259, new TreeNode<Hidden>({new TextCellRenderer("Teostra's Spada")}, new Hidden(258))},
        {260, new TreeNode<Hidden>({new TextCellRenderer("Teostra's Emblem")}, new Hidden(259))},
        {2238, new TreeNode<Hidden>({new TextCellRenderer("Teostra's Medal")}, new Hidden(260))},
        {261, new TreeNode<Hidden>({new TextCellRenderer("Xeno Mabura")}, new Hidden(258))},
        {1154, new TreeNode<Hidden>({new TextCellRenderer("Fatal Jho")}, new Hidden(-1))},
        {1155, new TreeNode<Hidden>({new TextCellRenderer("Fatal Bite")}, new Hidden(1154))},
        {2239, new TreeNode<Hidden>({new TextCellRenderer("Fate's Shear")}, new Hidden(1155))},
        {1198, new TreeNode<Hidden>({new TextCellRenderer("Empress Edge")}, new Hidden(-1))},
        {1199, new TreeNode<Hidden>({new TextCellRenderer("Empress Edge 'Blaze'")}, new Hidden(1198))},
        {2240, new TreeNode<Hidden>({new TextCellRenderer("Soulfire Barb 'Blaze'")}, new Hidden(1199))},
        {1200, new TreeNode<Hidden>({new TextCellRenderer("Empress Edge 'Ruin'")}, new Hidden(1198))},
        {2241, new TreeNode<Hidden>({new TextCellRenderer("Soulfire Barb 'Ruin'")}, new Hidden(1200))},
        {1201, new TreeNode<Hidden>({new TextCellRenderer("Empress Edge 'Styx'")}, new Hidden(1198))},
        {2242, new TreeNode<Hidden>({new TextCellRenderer("Soulfire Barb 'Styx'")}, new Hidden(1201))},
        {1258, new TreeNode<Hidden>({new TextCellRenderer("Witcher's Silver Sword")}, new Hidden(-1))},
        {1259, new TreeNode<Hidden>({new TextCellRenderer("Witcher's Silver Sword+")}, new Hidden(1258))},
        {2243, new TreeNode<Hidden>({new TextCellRenderer("Witcher's Silver Sword++")}, new Hidden(1259))},
        {3122, new TreeNode<Hidden>({new TextCellRenderer("Rajang Club")}, new Hidden(-1))},
        {3123, new TreeNode<Hidden>({new TextCellRenderer("Banned Rajang Club")}, new Hidden(3122))},
        {3124, new TreeNode<Hidden>({new TextCellRenderer("Demonlord Mace")}, new Hidden(-1))},
        {3125, new TreeNode<Hidden>({new TextCellRenderer("Brimstren Drakescale")}, new Hidden(-1))},
        {3126, new TreeNode<Hidden>({new TextCellRenderer("Stygian Luxuria")}, new Hidden(3125))},
        {3127, new TreeNode<Hidden>({new TextCellRenderer("Lightbreak Sword")}, new Hidden(-1))},
        {3198, new TreeNode<Hidden>({new TextCellRenderer("Alatreon Sword")}, new Hidden(-1))},
        {3199, new TreeNode<Hidden>({new TextCellRenderer("Alatreon Star")}, new Hidden(3198))},
        {3242, new TreeNode<Hidden>({new TextCellRenderer("Fatalis Sword")}, new Hidden(-1))},
        {3243, new TreeNode<Hidden>({new TextCellRenderer("True Fatalis Sword")}, new Hidden(3242))},
        {2244, new TreeNode<Hidden>({new TextCellRenderer("Guild Palace Sword")}, new Hidden(-1))},
        {2245, new TreeNode<Hidden>({new TextCellRenderer("Royal Nova Sword")}, new Hidden(2244))},
        {2246, new TreeNode<Hidden>({new TextCellRenderer("Defender Chainsaws I")}, new Hidden(-1))},
        {2247, new TreeNode<Hidden>({new TextCellRenderer("Defender Chainsaws II")}, new Hidden(2246))},
        {2248, new TreeNode<Hidden>({new TextCellRenderer("Defender Chainsaws III")}, new Hidden(2247))},
        {2249, new TreeNode<Hidden>({new TextCellRenderer("Defender Chainsaws IV")}, new Hidden(2248))},
        {2250, new TreeNode<Hidden>({new TextCellRenderer("Defender Chainsaws V")}, new Hidden(2249))},
        {262, new TreeNode<Hidden>({new TextCellRenderer("Matched Slicers I")}, new Hidden(-1))},
        {263, new TreeNode<Hidden>({new TextCellRenderer("Matched Slicers II")}, new Hidden(262))},
        {264, new TreeNode<Hidden>({new TextCellRenderer("Matched Slicers III")}, new Hidden(263))},
        {265, new TreeNode<Hidden>({new TextCellRenderer("Dual Slicers I")}, new Hidden(264))},
        {266, new TreeNode<Hidden>({new TextCellRenderer("Dual Slicers II")}, new Hidden(265))},
        {267, new TreeNode<Hidden>({new TextCellRenderer("Dual Slicers III")}, new Hidden(266))},
        {268, new TreeNode<Hidden>({new TextCellRenderer("Chrome Slicers I")}, new Hidden(267))},
        {269, new TreeNode<Hidden>({new TextCellRenderer("Chrome Slicers II")}, new Hidden(268))},
        {2251, new TreeNode<Hidden>({new TextCellRenderer("Chrome Cross I")}, new Hidden(269))},
        {2252, new TreeNode<Hidden>({new TextCellRenderer("Chrome Cross II")}, new Hidden(2251))},
        {2253, new TreeNode<Hidden>({new TextCellRenderer("Chrome Cross III")}, new Hidden(2252))},
        {2254, new TreeNode<Hidden>({new TextCellRenderer("Usurper's Fulgur")}, new Hidden(2251))},
        {2255, new TreeNode<Hidden>({new TextCellRenderer("Usurper's Fulgur+")}, new Hidden(2254))},
        {2256, new TreeNode<Hidden>({new TextCellRenderer("Despot's Blitz")}, new Hidden(2255))},
        {270, new TreeNode<Hidden>({new TextCellRenderer("Nergal Gouge")}, new Hidden(268))},
        {271, new TreeNode<Hidden>({new TextCellRenderer("Decimation Claws")}, new Hidden(270))},
        {2257, new TreeNode<Hidden>({new TextCellRenderer("Ruinous Decimation")}, new Hidden(271))},
        {272, new TreeNode<Hidden>({new TextCellRenderer("Luminous Daggers I")}, new Hidden(264))},
        {273, new TreeNode<Hidden>({new TextCellRenderer("Luminous Daggers II")}, new Hidden(272))},
        {274, new TreeNode<Hidden>({new TextCellRenderer("Dual Destroyers I")}, new Hidden(273))},
        {275, new TreeNode<Hidden>({new TextCellRenderer("Dual Destroyers II")}, new Hidden(274))},
        {276, new TreeNode<Hidden>({new TextCellRenderer("Dual Destroyers III")}, new Hidden(275))},
        {2258, new TreeNode<Hidden>({new TextCellRenderer("Cross Destroyers I")}, new Hidden(276))},
        {2259, new TreeNode<Hidden>({new TextCellRenderer("Cross Destroyers II")}, new Hidden(2258))},
        {2260, new TreeNode<Hidden>({new TextCellRenderer("Hidden Tomahawk I")}, new Hidden(2258))},
        {2261, new TreeNode<Hidden>({new TextCellRenderer("Hidden Tomahawk II")}, new Hidden(2260))},
        {277, new TreeNode<Hidden>({new TextCellRenderer("Rookslayer Handaxes")}, new Hidden(274))},
        {278, new TreeNode<Hidden>({new TextCellRenderer("Bazelhawk Rookslayer")}, new Hidden(277))},
        {2262, new TreeNode<Hidden>({new TextCellRenderer("Blazing Warhawks")}, new Hidden(278))},
        {2263, new TreeNode<Hidden>({new TextCellRenderer("Bazel Bombers")}, new Hidden(2262))},
        {279, new TreeNode<Hidden>({new TextCellRenderer("Freeze Daggers I")}, new Hidden(272))},
        {280, new TreeNode<Hidden>({new TextCellRenderer("Freeze Daggers II")}, new Hidden(279))},
        {281, new TreeNode<Hidden>({new TextCellRenderer("Freeze Chain I")}, new Hidden(280))},
        {282, new TreeNode<Hidden>({new TextCellRenderer("Freeze Chain II")}, new Hidden(281))},
        {2264, new TreeNode<Hidden>({new TextCellRenderer("Blizzarioths")}, new Hidden(282))},
        {2265, new TreeNode<Hidden>({new TextCellRenderer("Blizzarioths+")}, new Hidden(2264))},
        {2266, new TreeNode<Hidden>({new TextCellRenderer("Mountain Blizzarioths")}, new Hidden(2265))},
        {3225, new TreeNode<Hidden>({new TextCellRenderer("Bergel Vetra")}, new Hidden(2264))},
        {283, new TreeNode<Hidden>({new TextCellRenderer("Rending Beaks I")}, new Hidden(263))},
        {284, new TreeNode<Hidden>({new TextCellRenderer("Rending Beaks II")}, new Hidden(283))},
        {285, new TreeNode<Hidden>({new TextCellRenderer("Rending Beaks III")}, new Hidden(284))},
        {286, new TreeNode<Hidden>({new TextCellRenderer("Arcanaria I")}, new Hidden(285))},
        {287, new TreeNode<Hidden>({new TextCellRenderer("Arcanaria II")}, new Hidden(286))},
        {288, new TreeNode<Hidden>({new TextCellRenderer("Arcanaria III")}, new Hidden(287))},
        {2267, new TreeNode<Hidden>({new TextCellRenderer("Asefar al-Nasr I")}, new Hidden(288))},
        {2268, new TreeNode<Hidden>({new TextCellRenderer("Asefar al-Nasr II")}, new Hidden(2267))},
        {2269, new TreeNode<Hidden>({new TextCellRenderer("Rex Chain I")}, new Hidden(2267))},
        {2270, new TreeNode<Hidden>({new TextCellRenderer("Rex Chain II")}, new Hidden(2269))},
        {2271, new TreeNode<Hidden>({new TextCellRenderer("Accursed Chain")}, new Hidden(2269))},
        {2272, new TreeNode<Hidden>({new TextCellRenderer("Twin Flames")}, new Hidden(2267))},
        {2273, new TreeNode<Hidden>({new TextCellRenderer("Wyvern Lovers")}, new Hidden(2272))},
        {2274, new TreeNode<Hidden>({new TextCellRenderer("Wyvern Strife")}, new Hidden(2273))},
        {289, new TreeNode<Hidden>({new TextCellRenderer("Sworn Rapiers")}, new Hidden(283))},
        {290, new TreeNode<Hidden>({new TextCellRenderer("Sworn Rapiers+")}, new Hidden(289))},
        {291, new TreeNode<Hidden>({new TextCellRenderer("Holy Sabers")}, new Hidden(290))},
        {2275, new TreeNode<Hidden>({new TextCellRenderer("Guild Knight Sabers")}, new Hidden(291))},
        {2276, new TreeNode<Hidden>({new TextCellRenderer("Master Sabers")}, new Hidden(2275))},
        {2277, new TreeNode<Hidden>({new TextCellRenderer("Holy Guild Knight")}, new Hidden(2276))},
        {292, new TreeNode<Hidden>({new TextCellRenderer("Bone Hatchets I")}, new Hidden(-1))},
        {293, new TreeNode<Hidden>({new TextCellRenderer("Bone Hatchets II")}, new Hidden(292))},
        {294, new TreeNode<Hidden>({new TextCellRenderer("Bone Hatchets III")}, new Hidden(293))},
        {295, new TreeNode<Hidden>({new TextCellRenderer("Wild Hatchets I")}, new Hidden(294))},
        {296, new TreeNode<Hidden>({new TextCellRenderer("Wild Hatchets II")}, new Hidden(295))},
        {297, new TreeNode<Hidden>({new TextCellRenderer("Wild Hatchets III")}, new Hidden(296))},
        {298, new TreeNode<Hidden>({new TextCellRenderer("Strong Hatchets I")}, new Hidden(297))},
        {299, new TreeNode<Hidden>({new TextCellRenderer("Strong Hatchets II")}, new Hidden(298))},
        {2278, new TreeNode<Hidden>({new TextCellRenderer("Hulking Choppers I")}, new Hidden(299))},
        {2279, new TreeNode<Hidden>({new TextCellRenderer("Hulking Choppers II")}, new Hidden(2278))},
        {2280, new TreeNode<Hidden>({new TextCellRenderer("Hulking Choppers III")}, new Hidden(2279))},
        {2281, new TreeNode<Hidden>({new TextCellRenderer("Icefeather")}, new Hidden(2279))},
        {2282, new TreeNode<Hidden>({new TextCellRenderer("Untouched Hel")}, new Hidden(2281))},
        {300, new TreeNode<Hidden>({new TextCellRenderer("Blazing Hatchets I")}, new Hidden(294))},
        {301, new TreeNode<Hidden>({new TextCellRenderer("Blazing Hatchets II")}, new Hidden(300))},
        {302, new TreeNode<Hidden>({new TextCellRenderer("Anja Cyclone I")}, new Hidden(301))},
        {303, new TreeNode<Hidden>({new TextCellRenderer("Anja Cyclone II")}, new Hidden(302))},
        {304, new TreeNode<Hidden>({new TextCellRenderer("Anja Cyclone III")}, new Hidden(303))},
        {2283, new TreeNode<Hidden>({new TextCellRenderer("Anja Twinrippers I")}, new Hidden(304))},
        {2284, new TreeNode<Hidden>({new TextCellRenderer("Anja Twinrippers II")}, new Hidden(2283))},
        {2285, new TreeNode<Hidden>({new TextCellRenderer("Fulguring Tornado I")}, new Hidden(2283))},
        {2286, new TreeNode<Hidden>({new TextCellRenderer("Fulguring Tornado II")}, new Hidden(2285))},
        {305, new TreeNode<Hidden>({new TextCellRenderer("Diablos Hatchets I")}, new Hidden(300))},
        {306, new TreeNode<Hidden>({new TextCellRenderer("Diablos Hatchets II")}, new Hidden(305))},
        {307, new TreeNode<Hidden>({new TextCellRenderer("Diablos Clubs I")}, new Hidden(306))},
        {308, new TreeNode<Hidden>({new TextCellRenderer("Diablos Clubs II")}, new Hidden(307))},
        {2287, new TreeNode<Hidden>({new TextCellRenderer("Diablos Clubs III")}, new Hidden(308))},
        {2288, new TreeNode<Hidden>({new TextCellRenderer("Thanatos Mauls")}, new Hidden(2287))},
        {2289, new TreeNode<Hidden>({new TextCellRenderer("Sulfurteinn Ortho")}, new Hidden(2287))},
        {2290, new TreeNode<Hidden>({new TextCellRenderer("The Stripping Shears")}, new Hidden(2289))},
        {2291, new TreeNode<Hidden>({new TextCellRenderer("Mammoth Direbones I")}, new Hidden(308))},
        {2292, new TreeNode<Hidden>({new TextCellRenderer("Mammoth Direbones II")}, new Hidden(2291))},
        {309, new TreeNode<Hidden>({new TextCellRenderer("Madness Pangas I")}, new Hidden(293))},
        {310, new TreeNode<Hidden>({new TextCellRenderer("Madness Pangas II")}, new Hidden(309))},
        {311, new TreeNode<Hidden>({new TextCellRenderer("Madness Pangas III")}, new Hidden(310))},
        {312, new TreeNode<Hidden>({new TextCellRenderer("Jyura Hatchets I")}, new Hidden(311))},
        {313, new TreeNode<Hidden>({new TextCellRenderer("Jyura Hatchets II")}, new Hidden(312))},
        {314, new TreeNode<Hidden>({new TextCellRenderer("Jyura Hatchets III")}, new Hidden(313))},
        {2293, new TreeNode<Hidden>({new TextCellRenderer("Jyura Keenblades I")}, new Hidden(314))},
        {2294, new TreeNode<Hidden>({new TextCellRenderer("Jyura Keenblades II")}, new Hidden(2293))},
        {2295, new TreeNode<Hidden>({new TextCellRenderer("Raven Tessen")}, new Hidden(2293))},
        {2296, new TreeNode<Hidden>({new TextCellRenderer("Wolf Tessen")}, new Hidden(2295))},
        {2297, new TreeNode<Hidden>({new TextCellRenderer("Beo Hatchets I")}, new Hidden(314))},
        {2298, new TreeNode<Hidden>({new TextCellRenderer("Beo Hatchets II")}, new Hidden(2297))},
        {315, new TreeNode<Hidden>({new TextCellRenderer("Lava Cyclone I")}, new Hidden(312))},
        {316, new TreeNode<Hidden>({new TextCellRenderer("Lava Cyclone II")}, new Hidden(315))},
        {2299, new TreeNode<Hidden>({new TextCellRenderer("Shattering Flames I")}, new Hidden(316))},
        {2300, new TreeNode<Hidden>({new TextCellRenderer("Shattering Flames II")}, new Hidden(2299))},
        {2301, new TreeNode<Hidden>({new TextCellRenderer("Smoldering Cities")}, new Hidden(316))},
        {2302, new TreeNode<Hidden>({new TextCellRenderer("Smoldering Cities+")}, new Hidden(2301))},
        {2303, new TreeNode<Hidden>({new TextCellRenderer("Smoldering Kingdoms")}, new Hidden(2302))},
        {317, new TreeNode<Hidden>({new TextCellRenderer("Taurus Pangas I")}, new Hidden(309))},
        {318, new TreeNode<Hidden>({new TextCellRenderer("Taurus Pangas II")}, new Hidden(317))},
        {319, new TreeNode<Hidden>({new TextCellRenderer("Dark Ripper I")}, new Hidden(318))},
        {320, new TreeNode<Hidden>({new TextCellRenderer("Dark Ripper II")}, new Hidden(319))},
        {321, new TreeNode<Hidden>({new TextCellRenderer("Dark Ripper III")}, new Hidden(320))},
        {2304, new TreeNode<Hidden>({new TextCellRenderer("Abyss Eaters I")}, new Hidden(321))},
        {2305, new TreeNode<Hidden>({new TextCellRenderer("Abyss Eaters II")}, new Hidden(2304))},
        {2306, new TreeNode<Hidden>({new TextCellRenderer("Brachydios Blasters I")}, new Hidden(2304))},
        {2307, new TreeNode<Hidden>({new TextCellRenderer("Brachydios Blasters II")}, new Hidden(2306))},
        {322, new TreeNode<Hidden>({new TextCellRenderer("Pulsar Hatchets I")}, new Hidden(293))},
        {323, new TreeNode<Hidden>({new TextCellRenderer("Pulsar Hatchets II")}, new Hidden(322))},
        {324, new TreeNode<Hidden>({new TextCellRenderer("Pulsar Hatchets III")}, new Hidden(323))},
        {325, new TreeNode<Hidden>({new TextCellRenderer("Kadachi Claws I")}, new Hidden(324))},
        {326, new TreeNode<Hidden>({new TextCellRenderer("Kadachi Claws II")}, new Hidden(325))},
        {327, new TreeNode<Hidden>({new TextCellRenderer("Kadachi Claws III")}, new Hidden(326))},
        {2308, new TreeNode<Hidden>({new TextCellRenderer("Kadachi Greathawks I")}, new Hidden(327))},
        {2309, new TreeNode<Hidden>({new TextCellRenderer("Kadachi Greathawks II")}, new Hidden(2308))},
        {2310, new TreeNode<Hidden>({new TextCellRenderer("Crimson Viperclaws I")}, new Hidden(2308))},
        {2311, new TreeNode<Hidden>({new TextCellRenderer("Crimson Viperclaws II")}, new Hidden(2310))},
        {328, new TreeNode<Hidden>({new TextCellRenderer("Garon Hatchets I")}, new Hidden(323))},
        {329, new TreeNode<Hidden>({new TextCellRenderer("Garon Hatchets II")}, new Hidden(328))},
        {330, new TreeNode<Hidden>({new TextCellRenderer("Blood-drinker Chainblade")}, new Hidden(329))},
        {331, new TreeNode<Hidden>({new TextCellRenderer("Sin")}, new Hidden(330))},
        {2312, new TreeNode<Hidden>({new TextCellRenderer("Sin+")}, new Hidden(331))},
        {2313, new TreeNode<Hidden>({new TextCellRenderer("Crime")}, new Hidden(2312))},
        {2314, new TreeNode<Hidden>({new TextCellRenderer("Nether Chainblades")}, new Hidden(2312))},
        {2315, new TreeNode<Hidden>({new TextCellRenderer("Death Row")}, new Hidden(2314))},
        {332, new TreeNode<Hidden>({new TextCellRenderer("Dragonbone Twinblades I")}, new Hidden(-1))},
        {333, new TreeNode<Hidden>({new TextCellRenderer("Dragonbone Twinblades II")}, new Hidden(332))},
        {334, new TreeNode<Hidden>({new TextCellRenderer("Enduring Schism")}, new Hidden(333))},
        {2316, new TreeNode<Hidden>({new TextCellRenderer("Enduring Sacrifice")}, new Hidden(334))},
        {2317, new TreeNode<Hidden>({new TextCellRenderer("Enduring Surrender")}, new Hidden(2316))},
        {2318, new TreeNode<Hidden>({new TextCellRenderer("Boundless Farsight")}, new Hidden(2316))},
        {335, new TreeNode<Hidden>({new TextCellRenderer("Kirin Bolts")}, new Hidden(332))},
        {336, new TreeNode<Hidden>({new TextCellRenderer("Kirin Bolts+")}, new Hidden(335))},
        {337, new TreeNode<Hidden>({new TextCellRenderer("Monarch")}, new Hidden(336))},
        {2319, new TreeNode<Hidden>({new TextCellRenderer("Wunderkirins")}, new Hidden(337))},
        {338, new TreeNode<Hidden>({new TextCellRenderer("Magda Ungulae I")}, new Hidden(332))},
        {339, new TreeNode<Hidden>({new TextCellRenderer("Magda Ungulae II")}, new Hidden(338))},
        {2320, new TreeNode<Hidden>({new TextCellRenderer("Magdaros Volcancross")}, new Hidden(339))},
        {340, new TreeNode<Hidden>({new TextCellRenderer("Blacksteel Twins I")}, new Hidden(-1))},
        {341, new TreeNode<Hidden>({new TextCellRenderer("Blacksteel Twins II")}, new Hidden(340))},
        {342, new TreeNode<Hidden>({new TextCellRenderer("Twin Nails")}, new Hidden(341))},
        {343, new TreeNode<Hidden>({new TextCellRenderer("Fire and Ice")}, new Hidden(342))},
        {2321, new TreeNode<Hidden>({new TextCellRenderer("Blizzard and Blaze")}, new Hidden(343))},
        {344, new TreeNode<Hidden>({new TextCellRenderer("Xeno Raqs")}, new Hidden(341))},
        {1156, new TreeNode<Hidden>({new TextCellRenderer("Wrath & Rancor")}, new Hidden(-1))},
        {1157, new TreeNode<Hidden>({new TextCellRenderer("Wrathful Predation")}, new Hidden(1156))},
        {2322, new TreeNode<Hidden>({new TextCellRenderer("Consummate Pair")}, new Hidden(1157))},
        {1202, new TreeNode<Hidden>({new TextCellRenderer("Empress Daggers")}, new Hidden(-1))},
        {1203, new TreeNode<Hidden>({new TextCellRenderer("Empress Daggers 'Blaze'")}, new Hidden(1202))},
        {2323, new TreeNode<Hidden>({new TextCellRenderer("Soulfire Fangs 'Blaze'")}, new Hidden(1203))},
        {1204, new TreeNode<Hidden>({new TextCellRenderer("Empress Daggers 'Ruin'")}, new Hidden(1202))},
        {2324, new TreeNode<Hidden>({new TextCellRenderer("Soulfire Fangs 'Ruin'")}, new Hidden(1204))},
        {1205, new TreeNode<Hidden>({new TextCellRenderer("Empress Daggers 'Styx'")}, new Hidden(1202))},
        {2325, new TreeNode<Hidden>({new TextCellRenderer("Soulfire Fangs 'Styx'")}, new Hidden(1205))},
        {1206, new TreeNode<Hidden>({new TextCellRenderer("Downy Crake Brooms")}, new Hidden(-1))},
        {1207, new TreeNode<Hidden>({new TextCellRenderer("Downy Crake Love")}, new Hidden(1206))},
        {2326, new TreeNode<Hidden>({new TextCellRenderer("Downy Paradise")}, new Hidden(1207))},
        {1260, new TreeNode<Hidden>({new TextCellRenderer("Zireael")}, new Hidden(-1))},
        {2327, new TreeNode<Hidden>({new TextCellRenderer("Zireael+")}, new Hidden(1260))},
        {3128, new TreeNode<Hidden>({new TextCellRenderer("Suzuka Takamaru")}, new Hidden(-1))},
        {3129, new TreeNode<Hidden>({new TextCellRenderer("Suzuka Otakemaru")}, new Hidden(3128))},
        {3130, new TreeNode<Hidden>({new TextCellRenderer("Demonlord Hellfists")}, new Hidden(-1))},
        {3131, new TreeNode<Hidden>({new TextCellRenderer("Drakespirit Hellclaws")}, new Hidden(-1))},
        {3132, new TreeNode<Hidden>({new TextCellRenderer("Stygian Bloodclaws")}, new Hidden(3131))},
        {3133, new TreeNode<Hidden>({new TextCellRenderer("Lightbreak Twins")}, new Hidden(-1))},
        {3200, new TreeNode<Hidden>({new TextCellRenderer("Alatreon Dual Blades")}, new Hidden(-1))},
        {3201, new TreeNode<Hidden>({new TextCellRenderer("Alatreon Madness")}, new Hidden(3200))},
        {3244, new TreeNode<Hidden>({new TextCellRenderer("Fatalis Dual Blades")}, new Hidden(-1))},
        {3245, new TreeNode<Hidden>({new TextCellRenderer("Fatalis Dual Skies")}, new Hidden(3244))},
        {3134, new TreeNode<Hidden>({new TextCellRenderer("Whetfish Sabers")}, new Hidden(-1))},
        {3135, new TreeNode<Hidden>({new TextCellRenderer("Whetfish Sabers+")}, new Hidden(3134))},
        {2328, new TreeNode<Hidden>({new TextCellRenderer("Guild Palace Sabers")}, new Hidden(-1))},
        {2329, new TreeNode<Hidden>({new TextCellRenderer("Royal Savior Daggers")}, new Hidden(2328))},
    };

    Application *app = Application::get();
        app->mainWindow()->onReady = [&](Window *window) {
            if (argc > 1) {
                if (std::string(argv[1]) == std::string("quit")) {
                    window->quit();
                }
            }
        };
        app->mainWindow()->setTitle("TreeView");
        app->mainWindow()->resize(1200, 600);
        app->mainWindow()->center();
        TreeView<Hidden> *tv = new TreeView<Hidden>();
            auto c = new Column<Hidden>(
                "Name",
                nullptr,
                HorizontalAlignment::Center,
                [](TreeNode<Hidden> *lhs, TreeNode<Hidden> *rhs) {
                    return lhs->hidden->id > rhs->hidden->id;
                }
            );
            c->setExpand(true);
            tv->append(c);
            Tree<Hidden> *model = new Tree<Hidden>();
            for (auto pair : nodes) {
                if (pair.second->hidden->id == -1) {
                    model->append(nullptr, pair.second);
                } else {
                    model->append(nodes[pair.second->hidden->id], pair.second);
                }
            }
            tv->setModel(model);
        app->mainWindow()->append(tv, Fill::Both);
    app->run();

    return 0;
}
